name: Hello World
on: 
  push:
    branches:
     - main

jobs:
   Deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Setup   
      - run: echo "Hi Eric"
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Teardown
      - run: ls 
